apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-era
spec:
  replicas: {{ .Values.era.replicas }}
  selector:
    matchLabels:
      app: era
  template:
    metadata:
      labels:
        app: era
    spec:
      containers:
        - name: era
          image: {{ .Values.era.image }}
          env:
            - name: ERA_PORT
              value: "{{ .Values.era.port }}"

            - name: ERA_NATS_URL
              value: nats://{{ .Values.nats.host }}:{{ .Values.nats.port }}

            # - name: GITHUB_TOKEN
            #   valueFrom:
            #     secretKeyRef:
            #       name: {{ .Release.Name }}-github
            #       key: GITHUB_TOKEN       

            - name: ERA_LO_URL
              value: http://{{ .Values.era.lo.host }}:{{ .Values.era.lo.port }}
          ports:
            - containerPort: {{ .Values.era.port }}

      #     volumeMounts:
      #       - name: lo-data
      #         mountPath: /data

      # volumes:
      #   - name: lo-data
      #     persistentVolumeClaim:
      #       claimName: {{ .Release.Name }}-lo-data
