apiVersion: margo.edge/v1
kind: Deployment
metadata:
    name: Digitron orchestrator-deployment
    namespace: ""
    labels:
        app: Digitron orchestrator
    annotations:
        applicationId: com-northstartida-digitron-orchestrator
        id: c2bef716-eb6e-4bb3-ad26-eccfa3e25f8f
spec:
    deploymentProfile:
        type: compose
        components:
            - name: digitron-orchestrator-docker
              properties:
                packageLocation: https://northsitarida.com/digitron/docker/digitron-orchestrator.tar.gz
                keyLocation: https://northsitarida.com/digitron/docker/public-key.asc
    parameters:
        - name: SiteId
          value: 379871e1-d4c4-4cef-8545-353e4535f08e
          targets:
            - pointer: /sites/379871e1-d4c4-4cef-8545-353e4535f08e
              components: []
