log:
  level: debug
  format: text

nats:
  url: ss://localhost:4222
  username: test
  password: test123

lo:
  url: http://localhost:8081

host: 
  host_id: 554d7ac8-f261-44b0-a1f3-99d1175d2d59

