# boltdb:
#   path: 

# nats:
#   image: nats:2.10
#   port: 4222

# lo:
#   image: ghcr.io/balaji-balu/edgeorch-lo:latest
#   replicas: 1
#   port: 9010



site:
  name: site-1

github:
  token: ""   

nats:
  host: co-nats.default.svc.cluster.local
  port: 4222

lo:
  image: ghcr.io/balaji-balu/edgeorch-lo:latest
  replicas: 1
  port: 9010

  boltdb:
    path: /data/lo.db

  co:
    host: co-co.default.svc.cluster.local
    port: 9001

era:
  image: ghcr.io/balaji-balu/edgeorch-era:latest
  replicas: 1
  port: 9011

  lo:
    host: edgeorch-site-1-lo
    port: 9010