-- Create "sites" table
CREATE TABLE "sites" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "site_id" uuid NOT NULL,
  "name" character varying NULL,
  "description" character varying NULL,
  "location" character varying NULL,
  "orchestrator_id" uuid NULL,
  "metadata" jsonb NULL,
  "created_at" timestamptz NULL,
  "updated_at" timestamptz NULL,
  "orchestrator_sites" uuid NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "sites_orchestrator_sites" FOREIGN KEY ("orchestrator_sites") REFERENCES "orchestrator" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "sites_site_id_key" to table: "sites"
CREATE UNIQUE INDEX "sites_site_id_key" ON "sites" ("site_id");
-- Create "hosts" table
CREATE TABLE "hosts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "host_id" uuid NOT NULL,
  "site_id" uuid NOT NULL,
  "runtime" character varying NULL,
  "last_seen" timestamptz NULL,
  "misses" bigint NULL,
  "cpu_free" double precision NULL,
  "status" character varying NULL,
  "hostname" character varying NULL,
  "ip_address" character varying NULL,
  "edge_url" character varying NULL,
  "metadata" jsonb NULL,
  "created_at" timestamptz NULL,
  "updated_at" timestamptz NULL,
  "site_hosts" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "hosts_sites_hosts" FOREIGN KEY ("site_hosts") REFERENCES "sites" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "hosts_host_id_key" to table: "hosts"
CREATE UNIQUE INDEX "hosts_host_id_key" ON "hosts" ("host_id");
-- Drop "host" table
DROP TABLE "host";
-- Drop "site" table
DROP TABLE "site";
